# Generated by Django 4.1.3 on 2023-09-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'DEPOSIT'), (2, 'WITHDRAW')]),
        ),
    ]
